### PR TITLE
Attempt to improve device discovery

### PR DESCRIPTION
**Pull request by devbobo**
Move the wemo.discover() callback into it's own function so that wemo.discover() can be called multiple times.

### CODE REVIEW

**Comment by rudders** [comment]
Awesome mate. I'll merge this in the morning (Aus) and might make it an optional config param.

Node-SSDP has been updated too and I'd like to hook it in under WEMO-CLIENT when I get its error handling sorted. Need a clear head for that.

**Comment by devbobo** [comment]
does it need to be a configurable option ? i'd suggest just picking a number and running with it

**Comment by devbobo** [comment]
just being mindful of configuration overload....i doubt most people know what half the options do

**Comment by rudders** [comment]
Hey mate - what stops this adding a discovered device multiple times?

**Comment by devbobo** [comment]
I'm going to close this PR, as I believe that my `persist-devices` branch is the way forward

**Comment by rudders** [comment]
Oh and I was going to merge it this morning.....

**Pull request closed without merging**
