### PR TITLE
Added basic dimmer support

### PR DESCRIPTION
**Pull request by markhatchell**
Added demo dimmer as a switch for binary state options. No dimming support yet.

This PR is dependent on the PR in wemo-client  https://github.com/timonreinhard/wemo-client/pull/54 

Once that has been merged in to wemo-client then this can be merged in.

### CODE REVIEW

**Comment by devbobo** [comment]
@markhatchell just a heads up, I can't do anything with this PR until your PR on `wemo-client` has been merged.

**Comment by markhatchell** [comment]
No worries.  There may be some issue. I have been testing the dimmer and after a little while home bridge stops responding to HomeKit however doesn't crash. I'll report back here with more findings.

**Comment by markhatchell** [comment]
After more testing it appears I am having some other issues. This PR shouldn't be causing them, would be nice to have someone else with a dimmer test it out too though. Again only on-off support but, better then nothing. Might try to add dimming support too.

**Comment by lucanaut** [comment]
Hello, just wondering if this feature has been added and if so, how I could implement it.  I am running homebridge and the Wemo client but it's still telling me the dimmers are not supported.  Thank you!

**Comment by devbobo** [comment]
@lucanaut this PR is still open, therefore hasn't been merged into master.

**Comment by lucanaut** [comment]
I see thank you for the reply. Hope that moves forward!

**Comment by aguilucho2017** [comment]
Any news on this PR?.  0.1.4 of wemo-client was released already.

Thanks

**Comment by shivawu** [comment]
Ping as well. Hope this can be in soon

**Comment by kris2k2** [comment]
Hey all;

I can attest that the following addition works great for simple on/off operations having altered my own local code to successfully operate my two light dimmers.  
--
 +        case Wemo.DEVICE_TYPE.Dimmer:
 +            serviceType = Service.Switch;
 +            break;
--

**Comment by lucanaut** [comment]
Where did you add these lines?

**Pull request merged**
